-- MySQL Script generated by MySQL Workbench
-- lun 30 set 2019 11:46:59 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema matriculadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema matriculadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `matriculadb` ;
USE `matriculadb` ;

-- -----------------------------------------------------
-- Table `matriculadb`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `matriculadb`.`materias` (
  `id_materia` VARCHAR(5) NOT NULL,
  `nombre_materia` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
